version: "3.9"
services:
  openldap:
    image: "osixia/openldap"
    environment:
      LDAP_ORGANISATION: "SuperCoop Berlin"
      LDAP_DOMAIN: "supercoop.de"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_READONLY_USER: "true"
    ports:
      - "389:389"
    volumes:
      - ./docker/openldap/ldap_testdata.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-testdata.ldif
    # Required so that the container doesn't modify the testdata ldif
    command: --copy-service

  web:
    build: .
    command: bash -c "poetry install &&
                      poetry run python manage.py compilemessages --ignore \".venv\" &&
                      poetry run python manage.py runserver_plus 0.0.0.0:80"
    volumes:
      - .:/app
    environment:
      VIRTUAL_HOST: localhost
      DEBUG: 1
    depends_on:
      - openldap
      - db
      - selenium

  nginx-proxy:
    image: jwilder/nginx-proxy:1.2.3
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./docker/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./docker/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./docker/nginx/client_auth_certs:/etc/nginx/client_auth_certs:ro
      - ./docker/nginx/log:/var/log/nginx:rw
    ports:
      - "8000:80"
      - "8001:443"
      - 80
    environment:
      HTTPS_METHOD: noredirect
      DEFAULT_HOST: localhost
      DISABLE_ACCESS_LOGS: "true"

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=tapir
      - POSTGRES_PASSWORD=tapir
      - POSTGRES_USER=tapir
    ports:
      - '5432:5432'

  selenium:
    image: selenium/standalone-firefox-debug:latest
    shm_size: '2gb'
    ports:
      - 5900:5900 # VNC

  # Backend for Celery task queue
  redis:
    image: redis:alpine

  celery:
    build: .
    command: bash -c "poetry install &&
                      poetry run celery -A tapir worker -l info"
    volumes:
      - .:/app
    environment:
      DEBUG: 1
    depends_on:
      - redis

  celery-beat:
    build: .
    # --schedule to avoid polluting the app directory
    command: bash -c "poetry install &&
                      poetry run celery -A tapir beat -l info --schedule /tmp/celerybeat-schedule"
    volumes:
      - .:/app
    environment:
      DEBUG: 1
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
      - 9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - nginx-exporter

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    ports:
      - 9113
    command:
      - "-nginx.scrape-uri=http://nginx-proxy:80/metrics"
    depends_on:
      - nginx-proxy
    deploy:
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - "./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:rw"
      - "./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:rw"
      - "./docker/grafana/varlibgrafana:/etc/var/lib/grafana:rw"
    depends_on:
      - prometheus
      - nginx-exporter

volumes:
  nginx-certs-volume:
