# Generated by Django 3.2.12 on 2022-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0031_shiftattendance_last_state_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AlterField(
            model_name="shift",
            name="end_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="start_time",
            field=models.DateTimeField(db_index=True),
        ),
    ]
